trend_analysis_task:
  description: >
    Analyze the performance trends of the mentioned teams over their last 5 games.
    look for their win-loss records, key player statistics, recent game results
    Analyse the strong and weak points of the teams

    Outline structure:
      - Title: Last 5 game analysis of teams
      - Subtitle: Detailed analysis of trends, patterns, and key performance metrics from the last 5 games for the teams mentioned in {Question}.
      - Summary: Analyze the performance trends of the mentioned teams over their last 5 games.
      - Analysis: Statistics and insights on the performance metrics of the teams.
      - Conclusion: A detailed analysis of trends, patterns, and key performance metrics from the last 5 games for the teams mentioned in {Question}.
    
  expected_output: >
    Detailed analysis of trends, patterns, and key performance metrics from the last 5 games for the teams mentioned in {Question}.
  agent: trend_analysis_agent
  output_file: output/trend_analysis_report.md




team_changes_task:
  description: >
    Identify any recent team changes, player trades, or roster updates that could influence game outcomes within last 2 months.
    Look for the crucial players that have been traded, the teams that have been acquired, and the players that have been released.

    Outline structure:
      - Title: Team changes in last 2 months
      - Subtitle: Detailed analysis of team changes, player trades, or roster updates that could influence game outcomesfor the teams mentioned in {Question}.
      - Summary: Analyze the each change might affect the overall performance of the teams mentioned in {Question}
      - Analysis: Statistics and insights on the effect of the team changes on the game
      - Conclusion: A detailed analysis of consequences of team changes, player trades, or roster changes for the teams mentioned in {Question}.

  expected_output: >
     Detailed analysis of team changes, player trades, and their potential impact on team performance.
  agent: team_changes_agent
  output_file: output/team_changes_report.md




injury_analysis_task:
  description: >
    Analyze the injuries to players in the mentioned teams that could hamper performance.

    Identify any recent injuries or surgeries to players in the mentioned teams that could hamper performance and game outcomes within last 2 months.
    Look for the crucial players that have been injured or benched

    Outline structure:
      - Title: Injuries to players in last 2 months
      - Subtitle: Detailed analysis of play injuries, surgeries, or other changes that could influence game outcomesfor the teams mentioned in {Question}.
      - Summary: Analyze the each player that has been injured or benched might affect the overall performance of the teams mentioned in {Question}
      - Analysis: Statistics and insights on the effect of the player injuries on the team's perfromance
      - Conclusion: A detailed analysis of consequences of injuries or surgeries of crucial players for the teams mentioned in {Question}.

  expected_output: >
    Detailed report on player injuries from the teams mentioned in {Question}, including severity and impact on team dynamics.
  agent: injury_analysis_agent
  output_file: output/injury_analysis_report.md




head_to_head_analysis_task:
  description: >
    Analyze head-to-head match data from the last 2 years for the mentioned teams.
    look for their win-loss records, key player statistics, recent game results when the teams mentioned in {Question} faced each other

    Outline structure:
      - Title: Last 2 years head-to-head game analysis of teams
      - Subtitle: Detailed match analysis of key insights of the games, player performance, weather and venue for the teams mentioned in {Question} when they played against each other.
      - Summary: Analyze the win-loss statistics when the teams mentioned in {Question} faced each other. Derive insights on how it can impact the game mentioned in {Question}
      - Analysis: Statistics and insights on the head to head games between the teams mentioned in {Question}
      - Conclusion: A detailed analysis of trends, patterns, and key performance metrics from the head to head games for the teams mentioned in {Question}.

  expected_output: >
    Summary of performance trends, strategies, and key insights from past head-to-head encounters.
  agent: head_to_head_analysis_agent
  output_file: output/head_to_head_analysis_report.md




current_season_performance_task:
  description: >
    Evaluate the current season performance of the mentioned teams, focusing on key metrics like wins, losses, and points scored.
    look for their win-loss records this season, key player statistics of this current season, recent game results when the teams mentioned in {Question}
    Analyse the reason of the loss and their win

    Outline structure:
      - Title: Current season performance of teams
      - Subtitle: Detailed analysis of key insights of the games, player perfromance, weather and venue for the teams mentioned in {Question} that lead to the current season performance.
      - Summary: Analyze the win-loss statistics when the teams mentioned in {Question} in the current season. Derive insights on how it can impact the game mentioned in {Question}
      - Analysis: Statistics and insights on the performance and it's consequences
      - Conclusion: A detailed analysis reviewing the current performance of the teams mentioned in {Question}.

  expected_output: >
    Detailed report on the current season performance metrics, highlighting trends and critical data.
  agent: current_season_performance_agent
  output_file: output/current_season_performance_report.md




coaching_strategy_task:
  description: >
    Analyze coaching strategies and decisions that could strategically affect team performance.
    look for startegic moves that worked in favour for or against the teams mentioned in {Question}
    Analyse what could have been better in startegy

    Outline structure:
      - Title: Coaching stategies and decision of teams
      - Subtitle: Detailed analysis of key improvements, decisions, startegies that worked for the teams mentioned in {Question} that lead to a win
      - Summary: Analyze the startegy that worked, that didnot worked, that could have been executed better for the teams mentioned in {Question} in the current season. Derive insights on how it can impact the game mentioned in {Question}
      - Analysis: Statistics and insights of the coaching strategies on the performance and it's consequences
      - Conclusion: A detailed analysis reviewing the coaching strategies of the teams mentioned in {Question}.

  expected_output: >
    Insights into coaching approaches, tactical decisions, and their impact on the teams' performance.
  agent: coaching_strategy_analysis_agent
  output_file: output/coaching_strategy_report.md




environmental_impact_task:
  description: >
    Analyze the impact of venue, weather, humidity, and other environmental factors on team performance.
    look for what kind of weather, venue and conditions that worked in favour for or against the teams mentioned in {Question}
    Analyse why certain conditions can favour the teams mentioned in {Question}

    Outline structure:
      - Title: Impact of venue, weather, humidity and playing condition of teams
      - Subtitle: Detailed analysis of key environmental factors and how it can affect the teams performance mentioned in {Question}
      - Summary: Analyze the what conditions are suitable for the teams mentioned in {Question}. Home venue will be better for home team 
      - Analysis: Analyze the current weather conditions of the venue and derive how it will affect the game
      - Conclusion: A detailed analysis reviewing the environmental condition like weather, climate, humidity, venue on the teams mentioned in {Question}.

  expected_output: >
    Assessment of environmental conditions and their strategic or physical influence on the teams' performance.
  agent: environmental_impact_analysis_agent
  output_file: output/environmental_impact_report.md




performance_summary_task:
  description: >
    Aggregate the outputs of all specialized agents to provide a detailed summary of factors affecting team performance.
  expected_output: >
    Comprehensive and integrated summary of all key factors influencing the teams' performance, covering trends, injuries, strategies, environmental factors

    Outline structure:
      - Title: Summary of the factors affecting the teams' performance
      - Subtitle: Detailed analysis of injureis, team changes, player changes, weather and environmental conditions, coaching startegy and how it can affect the teams performance mentioned in {Question}
      - Summary: Summarize the factors that can affect the teams' performance and derive who can win out of the teams mentioned in {Question}
      - Analysis: Analyze all the reports carefully and derive decisions making information that can help in deciding who might win the game
      - Conclusion: A detailed analysis reviewing all the factors affecting the teams mentioned in {Question}.

  agent: performance_summary_agent
  context:
    - trend_analysis_task
    - injury_analysis_task
    - head_to_head_analysis_task
    - current_season_performance_task
    - coaching_strategy_task
    - environmental_impact_task
  output_file: output/performance_summary_report.md




consensus_summary_task:
  description: >
    Derive insights from output of performance_summary_agent
  expected_output: >
    A detailed summary of the key factors influencing the teams' performance based on the output of performance_summary_agent
  agent: consensus_agent
  context:
    - performance_summary_task
  output_file: output/final_report.md
